"""article dans elements et correction visuel

Revision ID: 003710c65e2e
Revises: 62bbce1a3e76
Create Date: 2024-12-29 17:28:43.957969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003710c65e2e'
down_revision = '62bbce1a3e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])
        batch_op.create_foreign_key(None, 'conferences', ['conference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
