"""Theme evenement

Revision ID: 064e696199be
Revises: a1f74de332d9
Create Date: 2024-12-28 23:26:11.462692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064e696199be'
down_revision = 'a1f74de332d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Text(), nullable=True))

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conferences', ['conference_id'], ['id'])
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
