"""Add article column to Conference

Revision ID: 6ff9b8078f76
Revises: f4debba1fb51
Create Date: 2024-12-20 15:14:22.136898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff9b8078f76'
down_revision = 'f4debba1fb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', sa.Text(), nullable=True))

    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('article')

    # ### end Alembic commands ###
