"""Ajout du modèle Visual

Revision ID: c0dd2339479e
Revises: 6ff9b8078f76
Create Date: 2024-12-20 16:14:49.985766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dd2339479e'
down_revision = '6ff9b8078f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('associated_type', sa.String(length=50), nullable=True),
    sa.Column('associated_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visuals')
    # ### end Alembic commands ###
