"""Ajout de target_audience pour les communiqués de presse

Revision ID: ebb4e9edeaca
Revises: 3f7a38b62e39
Create Date: 2024-12-28 19:20:32.845872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb4e9edeaca'
down_revision = '3f7a38b62e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(length=100), nullable=True))

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
