"""Ajout de la table Evenement et mise à jour des relations

Revision ID: fe97a7fcc24f
Revises: c0dd2339479e
Create Date: 2024-12-23 19:00:46.324167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe97a7fcc24f'
down_revision = 'c0dd2339479e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evenement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evenement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])

    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evenement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evenements', ['evenement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evenement_id')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evenement_id')

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evenement_id')

    op.drop_table('evenements')
    # ### end Alembic commands ###
